apiVersion: v1
kind: Service
metadata:
  name: meu-servico
spec:
  selector:
    app: minha-aplicacao
  ports:
    - protocol: TCP
      port: 8080         # Porta interna que o Service expõe dentro do cluster
      targetPort: 8080   # Porta interna do container (a mesma da API)
      nodePort: 31234    # Porta no nó do Kubernetes para acesso externo (fora do cluster)
  type: NodePort        # Tipo de Service para expor a aplicação externamente
